// Auto-generated by Google Maps AI Pipeline v4.0
export const businessData = {
  name: "Matrix Digital",
  category: "Digital Marketing Agency",
  address: "401 Tech Park, SG Highway, Ahmedabad, Gujarat",
  phone: "+91 98765 43210",
  email: "",
  website: "",
  mapUrl: "",
  latitude: "",
  longitude: "",
  rating: "4.8",
  reviewsCount: "320",
  openingHours: "",
  logo: null,
  images: [],
  description: "Full-service digital marketing and web development agency",
  socials: {},
};

export const aiContent = {
  tagline: "Transforming Tech Park",
  heroDescription: "Located in the heart of 401 Tech Park, SG Highway, Ahmedabad, Gujarat, Matrix Digital is a full-service digital marketing and web development agency dedicated to driving business growth. Our team of experts leverages cutting-edge technology to deliver innovative solutions. With a strong focus on customer satisfaction, we strive to exceed expectations.",
  aboutTitle: "Empowering Digital Excellence",
  aboutText: "At Matrix Digital, we're passionate about helping businesses thrive in the digital landscape. Situated in the vibrant 401 Tech Park, our agency is nestled in a hub of technological innovation. Our team of skilled professionals is committed to delivering tailored solutions that meet the unique needs of each client. With a deep understanding of the local market, we're well-equipped to drive success for businesses in Ahmedabad and beyond.",
  services: [
    { icon: "📈", title: "Digital Marketing Strategy", description: "Our team develops customized digital marketing plans that align with your business goals, targeting the Gujarat market and beyond." },
    { icon: "🌐", title: "Web Development", description: "We design and build responsive, user-friendly websites that showcase your brand and drive conversions, optimized for the Indian market." },
    { icon: "📊", title: "Data Analysis and Reporting", description: "Our experts provide in-depth data analysis and reporting, helping you make informed decisions and drive business growth, with a focus on the Ahmedabad market." },
    { icon: "📱", title: "Mobile App Development", description: "We create innovative, engaging mobile apps that enhance your brand's presence and drive customer engagement, tailored to the Indian mobile market." },
    { icon: "📢", title: "Social Media Management", description: "Our team develops and implements effective social media strategies that build your brand and drive customer interaction, with a focus on the Gujarat region." },
    { icon: "🔒", title: "Cybersecurity Solutions", description: "We provide comprehensive cybersecurity solutions to protect your business from online threats, ensuring the security and integrity of your data." }
  ],
  whyChooseUs: [
    { icon: "🏙️", title: "Strategic Location", description: "Our location in 401 Tech Park, Ahmedabad, allows us to stay at the forefront of technological innovation and provide our clients with cutting-edge solutions." },
    { icon: "💡", title: "Innovative Approach", description: "Our team of experts is committed to delivering innovative, tailored solutions that meet the unique needs of each client, driving business growth and success." },
    { icon: "📈", title: "Data-Driven Results", description: "We focus on delivering measurable, data-driven results that demonstrate the effectiveness of our digital marketing and web development solutions." },
    { icon: "🤝", title: "Personalized Service", description: "At Matrix Digital, we pride ourselves on providing personalized service and support to each of our clients, ensuring their needs are met and exceeded." }
  ],
  testimonials: [
    { name: "Mihir Mehta", role: "CEO, Ahmedabad-based startup", text: "Matrix Digital's digital marketing strategy has been instrumental in driving our business growth. Their team is knowledgeable, responsive, and dedicated to delivering results. We've seen a significant increase in website traffic and conversions since partnering with them.", rating: 5 },
    { name: "Mahesh Patel", role: "Marketing Manager, Gujarat-based corporation", text: "The web development team at Matrix Digital is exceptional. They designed and built a responsive, user-friendly website that showcases our brand and drives customer engagement. We're extremely satisfied with the final product and the service we received.", rating: 5 },
    { name: "Manisha Sharma", role: "Founder, e-commerce startup", text: "Matrix Digital's social media management services have helped us build a strong online presence and drive customer interaction. Their team is creative, responsive, and always willing to go the extra mile to ensure our success.", rating: 5 }
  ],
  faq: { items: [{ question: "What services does Matrix Digital offer?", answer: "Matrix Digital is a full-service digital marketing and web development agency, offering a range of services including digital marketing strategy, web development, data analysis and reporting, mobile app development, social media management, and cybersecurity solutions." },
    { question: "How do I get in touch with Matrix Digital?", answer: "You can contact Matrix Digital by calling +91 98765 43210 or visiting our office at 401 Tech Park, SG Highway, Ahmedabad, Gujarat." },
    { question: "What is the cost of Matrix Digital's services?", answer: "The cost of our services varies depending on the specific solution and the needs of each client. Our pricing ranges from ₹524 to ₹4488, and we offer customized packages to fit each client's budget and requirements." },
    { question: "Does Matrix Digital have experience working with businesses in Ahmedabad?", answer: "Yes, Matrix Digital has extensive experience working with businesses in Ahmedabad and the surrounding areas. Our team has a deep understanding of the local market and is well-equipped to drive success for businesses in the region." },
    { question: "How long does it take to see results from Matrix Digital's services?", answer: "The time it takes to see results from our services varies depending on the specific solution and the goals of each client. However, our team is committed to delivering measurable, data-driven results and providing regular updates and progress reports to ensure our clients are informed and satisfied." },
    { question: "Does Matrix Digital offer any guarantees or warranties?", answer: "Yes, Matrix Digital offers a satisfaction guarantee for all of our services. If our clients are not satisfied with the work we've done, we'll work with them to revise and improve the solution until they're satisfied." }] },
  ctaTitle: "Transform Your Business",
  ctaDescription: "Get in touch with us to learn more about our digital marketing and web development services and discover how we can help drive your business growth.",
  ctaButtonText: "Get Started Today",
  metaDescription: "Matrix Digital: Ahmedabad's leading digital marketing and web development agency",
};

export const siteConfig = {
  layout: "interactive-3d",
  theme: "elegant",
  sections: ["services", "contact", "faq", "about", "testimonials"],
  heroVariant: "testimonial-first",
  navStyle: "floating-pill",
  animationStyle: "slide-in-left-right",
  cardStyle: "rounded-none border-l-4 border-l-primary",
  darkMode: true,
};
